apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-service
  namespace: vercel-clone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: build-service
  template:
    metadata:
      labels:
        app: build-service
    spec:
      containers:
      - name: build-service
        image: filoraxx/build-service:1.0
        ports:
        - containerPort: 8082
        env:
        - name: DOCKERHUB_REGISTRY
          valueFrom:
            configMapKeyRef:
              name: registry-config
              key: dockerhub-registry
        - name: SPRING_REDIS_HOST
          value: "redis"
        - name: CLOUDFLARE_R2_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: r2-credentials
              key: endpoint
        - name: CLOUDFLARE_R2_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: r2-credentials
              key: access-key
        - name: CLOUDFLARE_R2_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: r2-credentials
              key: secret-key
        - name: CLOUDFLARE_R2_BUCKET
          valueFrom:
            secretKeyRef:
              name: r2-credentials
              key: bucket
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: secret
        - name: JWT_EXPIRATION
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: expiration
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
