apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: vercel-clone
data:
  dockerhub-registry: "YOUR_DOCKERHUB"
  upload-service-image: "YOUR_DOCKERHUB/upload-service:v1"
  build-service-image: "YOUR_DOCKERHUB/build-service:v1"
  request-handler-image: "YOUR_DOCKERHUB/request-handler:v1"
