apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: vercel-clone
data:
  dockerhub-registry: "filoraxx"
  upload-service-image: "filoraxx/upload-service:1.0"
  build-service-image: "filoraxx/build-service:1.0"
  request-handler-image: "filoraxx/request-handler:1.0"
  frontend-image: "filoraxx/frontend:1.0"
